### ISSUE TITLE
Download is freeze when bad network

### ISSUE THREAD

**Issue by veila** [chasseurmic/TWRDownloadManager#39]
Hi,
I test my app switch between  good network. -> bad network -> good network.
first, all files downloading, then I change to bad network.
all files in current download is freeze (it's right). But when I change back to good network. Some files download good, but some files still freeze. I thought these files stop download, I just check them "isFileDownloadingForUrl" or not then "downloadFileForURL" again. But I check them still downloading and in array current download.
If want these download finish. I have to stop and redownload all. That not good with user. Please help

**Comment by samisharafeddine** [comment]
The connection would appear to be terminated by the server.. nothing much to do here since its the server's configuration that acts this way, the problem is not from TWRDownloadManager

**Comment by veila** [comment]
Ok I understand now. Thanks for supporting
