### ISSUE TITLE
uitableviewcell  example

### ISSUE THREAD

**Issue by syrakozz** [chasseurmic/TWRDownloadManager#9]
could you please add an uitableviewcell exmaple to the project, 
im using the uitableviewcell but when i press back and then i return i got sigbart exception, 
please help

**Comment by Badasme** [comment]
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath
{
    DownloadCell *cell = [tableView dequeueReusableCellWithIdentifier:@"DownloadCell" forIndexPath:indexPath];
    
    NSString *url = [TWRDownloadManager sharedManager].currentDownloads[indexPath.row];
    
    [[TWRDownloadManager sharedManager] isFileDownloadingForUrl:url withProgressBlock:cell.progressBlock completionBlock:cell.completionBlock];
    
    cell.downloadscelllabel.text=url.lastPathComponent;
    return cell;
}

**Comment by eqenkhjin** [comment]
Updated answer @Badasme 

Before call this function.
[[TWRDownloadManager sharedManager] isFileDownloadingForUrl:url withProgressBlock:cell.progressBlock completionBlock:cell.completionBlock];

You must set nil uitableviewcell's blocks;

cell.progressBlock = nil;
cell.completionBlock = nil;

Full code : 

(UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath
{
DownloadCell *cell = [tableView dequeueReusableCellWithIdentifier:@"DownloadCell" forIndexPath:indexPath];

//bottom line is incorrect @Badasme 
NSString *url = [TWRDownloadManager sharedManager].currentDownloads[indexPath.row];

cell.progressBlock = nil;
cell.completionBlock = nil;

[[TWRDownloadManager sharedManager] isFileDownloadingForUrl:url withProgressBlock:cell.progressBlock completionBlock:cell.completionBlock];

cell.downloadscelllabel.text=url.lastPathComponent;
return cell;
}
